data_vault:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: abc123
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
      connect_timeout: 10 